# Generated by Django 2.0.4 on 2018-06-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='active_pin',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
