# Generated by Django 2.0.4 on 2018-06-07 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customer_active_pin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='active_pin',
        ),
    ]
