# Generated by Django 2.0.4 on 2018-06-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180607_1750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AddField(
            model_name='customer',
            name='act_code',
            field=models.CharField(default='_', max_length=255, verbose_name='act_code'),
        ),
    ]
