# Generated by Django 2.0.4 on 2018-05-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Category', max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
