# Generated by Django 2.0.4 on 2018-05-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NoName', max_length=255)),
                ('phone', models.CharField(default='+7 000 000 00 00', max_length=20)),
                ('email', models.EmailField(default='mail@mail.ru', max_length=255)),
            ],
        ),
    ]
